version: '3'
services:
  db:
    container_name: mysql
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=12345678
    volumes:
    - /tmp/mysql:/var/lib/mysql
  sequelize:
    container_name: s1
    build: .
    ports:
    - 3000:3000
    links:
    - db
    volumes:
    - /home/david/node-sequelize:/app
    environment:
    - DB_PASSWORD=12345678
    - DB_USER=node
    - DB_HOST=mysql
    - DB_PORT=3306
 